In [120]:
#Primero tenemos que mandar a traer las librerias que ocuparemos para manipular los datos
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [121]:
%pip install matplotlib #Dado a que me marcaba un error arriba, tuve que instalar ambas biblitecas
%pip install seaborn

Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (2.2.2)
Requirement already satisfied: packaging>=20.0 in /Users/borregof/Library/Python/3.13/lib/python/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/borregof/Library/Python/3.13/lib/python/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/borregof/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from seaborn) (2.2.2)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /Users/borregof/Library/Python/3.13/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/borregof/Library/Python/3.13/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: six>=1.5 in /Users/borregof/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
#Para poder manipular los datos, tenemos que hacer que python lea el CSV (sé que suena a IA la instrucción pero le prometo que solo así me explico)
df= pd.read_csv('Boston_United States.csv') 
df

,Unnamed: 0,last_scraped,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,...,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,0,2024-12-20,2008-12-03,"Massachusetts, United States",within a day,100%,22%,t,East Boston,2,...,1,0,2015-07-10,2024-08-09,4.96,5.00,5.00,4.96,4.85,4.88
1,1,2024-12-20,2009-02-19,"Boston, MA",within an hour,100%,99%,t,Roxbury,11,...,10,0,2009-03-21,2024-10-19,4.81,4.88,4.95,4.89,4.56,4.76
2,2,2024-12-20,2009-02-19,"Boston, MA",within an hour,100%,99%,t,Roxbury,11,...,8,0,2009-08-06,2024-11-11,4.81,4.83,4.91,4.95,4.53,4.72
3,3,2024-12-20,2009-07-22,"Boston, MA",within a few hours,100%,49%,t,Beacon Hill,8,...,1,0,2014-08-12,2024-05-15,4.69,4.69,4.93,4.97,4.97,4.59
4,4,2024-12-20,2009-09-16,NaN,within a day,91%,58%,f,Back Bay,22,...,0,0,2016-01-09,2019-07-22,4.33,4.44,4.56,4.00,5.00,4.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4421,4421,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4422,4422,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4423,4423,2024-12-20,2018-08-29,"Boston, MA",within an hour,100%,98%,f,Theater District,162,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4424,4424,2024-12-20,2016-05-29,NaN,within an hour,100%,100%,t,Roslindale,2,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4425,4425,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Ya que como no elegí el nombre de los hos como variable, opte por elegir el vecindario como filtro, pero a la hora de intentar hacer el filtro
#como intente hacer la comparativa pero mostraba un error de longitud de datos, opte por crear data frames con el atributo de la selección de nombres
df1 = [df[df["host_neighbourhood"] == "Back Bay"],
      df[df["host_neighbourhood"] == "Dorchester"],
      df[df["host_neighbourhood"] == "Roxbury"],
      df[df["host_neighbourhood"] == "Jamaica Plain"],
      df[df["host_neighbourhood"] == "North End"]]

df1_listo = pd.concat(df1) #Uní todos los frames con un .concat

In [ ]:
#Una vez listo ya solo lo exporte en forma de csv
df1_listo.to_csv("Primer_punto.csv", index=False)

In [ ]:
#Aquí cree el segundo filtro en el que la columna de host_since solo dejará los valores que correspondan despues del primero de enero de 2020, para así saber de los host registrados desde 2020 para adelante
df2 = df[df['host_since'] > '2020-01-01']
df2

,Unnamed: 0,last_scraped,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,...,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
573,573,2024-12-20,2022-02-21,NaN,NaN,NaN,NaN,f,NaN,1,...,51,2,2017-11-20,2024-12-08,4.98,4.96,4.93,4.93,4.75,4.9
1343,1343,2024-12-20,2020-01-28,NaN,NaN,NaN,NaN,f,North End,1,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1344,1344,2024-12-20,2020-01-30,NaN,NaN,NaN,NaN,f,Mission Hill,1,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1355,1355,2024-12-20,2020-02-16,"Boston, MA",NaN,NaN,NaN,f,NaN,1,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1377,1377,2024-12-20,2020-03-17,NaN,NaN,NaN,NaN,f,Beacon Hill,1,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4417,4417,2024-12-20,2024-12-13,NaN,NaN,NaN,100%,f,South Boston,2,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4420,4420,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4421,4421,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4422,4422,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4425,4425,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Una vez listo ya solo lo exporte en forma de csv
df2.to_csv("Punto 2.csv")

In [ ]:
#Primero cree un "nuevo data Frame" ya que quería hacer manipulable la columna del host response time, ya que queríe elegir todos los tiempos que correspondieran o enteraran a menos de un día de respuesta
df1= pd.read_csv('Boston_United States.csv',index_col=4)
df1

,Unnamed: 0,last_scraped,host_since,host_location,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,...,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
host_response_time,,,,,,,,,,,,,,,,,,,,,
within a day,0,2024-12-20,2008-12-03,"Massachusetts, United States",100%,22%,t,East Boston,2,6,...,1,0,2015-07-10,2024-08-09,4.96,5.00,5.00,4.96,4.85,4.88
within an hour,1,2024-12-20,2009-02-19,"Boston, MA",100%,99%,t,Roxbury,11,14,...,10,0,2009-03-21,2024-10-19,4.81,4.88,4.95,4.89,4.56,4.76
within an hour,2,2024-12-20,2009-02-19,"Boston, MA",100%,99%,t,Roxbury,11,14,...,8,0,2009-08-06,2024-11-11,4.81,4.83,4.91,4.95,4.53,4.72
within a few hours,3,2024-12-20,2009-07-22,"Boston, MA",100%,49%,t,Beacon Hill,8,32,...,1,0,2014-08-12,2024-05-15,4.69,4.69,4.93,4.97,4.97,4.59
within a day,4,2024-12-20,2009-09-16,NaN,91%,58%,f,Back Bay,22,29,...,0,0,2016-01-09,2019-07-22,4.33,4.44,4.56,4.00,5.00,4.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
within an hour,4421,2024-12-20,2020-10-28,"Boston, MA",100%,97%,f,Harvard Square,199,355,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
within an hour,4422,2024-12-20,2020-10-28,"Boston, MA",100%,97%,f,Harvard Square,199,355,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
within an hour,4423,2024-12-20,2018-08-29,"Boston, MA",100%,98%,f,Theater District,162,226,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
within an hour,4424,2024-12-20,2016-05-29,NaN,100%,100%,t,Roslindale,2,2,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
within an hour,4425,2024-12-20,2020-10-28,"Boston, MA",100%,97%,f,Harvard Square,199,355,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Aquí hice el filtro un avez listos los datos para ser manipulados e incluí las variables que antes mencioné
df3= df1.loc[['within a day', 'within a few hours', 'within an hour']]
df3

,Unnamed: 0,last_scraped,host_since,host_location,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,...,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
host_response_time,,,,,,,,,,,,,,,,,,,,,
within a day,0,2024-12-20,2008-12-03,"Massachusetts, United States",100%,22%,t,East Boston,2,6,...,1,0,2015-07-10,2024-08-09,4.96,5.00,5.00,4.96,4.85,4.88
within a day,4,2024-12-20,2009-09-16,NaN,91%,58%,f,Back Bay,22,29,...,0,0,2016-01-09,2019-07-22,4.33,4.44,4.56,4.00,5.00,4.67
within a day,5,2024-12-20,2009-09-16,NaN,91%,58%,f,Back Bay,22,29,...,0,0,2019-03-17,2023-11-19,5.00,5.00,5.00,5.00,5.00,4.80
within a day,6,2024-12-20,2009-09-16,NaN,91%,58%,f,Back Bay,22,29,...,1,0,2024-01-05,2024-01-05,4.00,5.00,2.00,5.00,5.00,4.00
within a day,7,2024-12-20,2010-01-19,"Boston, MA",100%,97%,f,Dorchester,39,75,...,0,0,2010-05-12,2023-08-19,4.31,4.50,4.56,4.46,4.24,4.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
within an hour,4421,2024-12-20,2020-10-28,"Boston, MA",100%,97%,f,Harvard Square,199,355,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
within an hour,4422,2024-12-20,2020-10-28,"Boston, MA",100%,97%,f,Harvard Square,199,355,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
within an hour,4423,2024-12-20,2018-08-29,"Boston, MA",100%,98%,f,Theater District,162,226,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
within an hour,4424,2024-12-20,2016-05-29,NaN,100%,100%,t,Roslindale,2,2,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
within an hour,4425,2024-12-20,2020-10-28,"Boston, MA",100%,97%,f,Harvard Square,199,355,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Una vez listo ya solo lo exporte en forma de csv
df3.to_csv("Tercer_punto.csv")

In [ ]:
#Alguien en la clase comentó que lo hizon los residuos así que robe el tip y solo puse que el residuo fuera igual a 0 si se dividía entre 0 y le indique que los número que dicidiría serían los indíces
df4 = df[df.index % 200 == 0] 
df4

,Unnamed: 0,last_scraped,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,...,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,0,2024-12-20,2008-12-03,"Massachusetts, United States",within a day,100%,22%,t,East Boston,2,...,1,0,2015-07-10,2024-08-09,4.96,5.00,5.00,4.96,4.85,4.88
200,200,2024-12-20,2015-03-18,"Boston, MA",within a few hours,100%,100%,t,South Boston,1,...,19,0,2017-08-28,2024-11-12,4.86,4.88,4.97,4.97,4.89,4.75
400,400,2024-12-20,2014-06-16,"Boston, MA",NaN,NaN,NaN,f,NaN,1,...,0,0,2018-10-14,2018-10-28,5.00,5.00,5.00,5.00,5.00,5.00
600,600,2024-12-20,2014-07-21,"Boston, MA",within an hour,91%,0%,f,Roxbury,31,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
800,800,2024-12-20,2009-09-16,NaN,within a day,91%,58%,f,Back Bay,22,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,1000,2024-12-20,2018-10-11,"Boston, MA",within an hour,100%,99%,t,West Roxbury,4,...,9,2,2018-10-14,2024-12-03,4.77,4.87,4.93,4.92,4.70,4.77
1200,1200,2024-12-20,2017-10-12,"Boston, MA",NaN,NaN,NaN,f,South Boston,1,...,0,0,2019-08-18,2019-08-27,5.00,5.00,5.00,5.00,5.00,4.50
1400,1400,2024-12-20,2014-06-17,"Palm Springs, CA",within an hour,100%,100%,t,Fort Point,2,...,0,0,2022-05-17,2023-12-17,5.00,5.00,5.00,5.00,5.00,4.75
1600,1600,2024-12-20,2020-07-21,NaN,within an hour,100%,100%,t,Brighton,8,...,17,0,2021-04-18,2024-11-17,4.93,4.91,4.97,4.93,4.88,4.84
1800,1800,2024-12-20,2017-05-21,"Massachusetts, United States",within an hour,100%,88%,t,Lower Allston,2,...,1,0,2021-11-13,2024-08-24,4.40,4.20,4.80,5.00,4.20,4.00
2000,2000,2024-12-20,2012-08-29,"Newton, MA",within an hour,100%,76%,f,Fenway–Kenmore,3,...,0,0,2022-09-06,2022-09-06,3.00,3.00,5.00,2.00,5.00,4.00
2200,2200,2024-12-20,2019-06-04,"Boston, MA",within an hour,100%,89%,f,Brookline,79,...,0,0,2023-10-22,2023-11-12,5.00,4.25,4.75,5.00,5.00,4.50
2400,2400,2024-12-20,2018-08-29,"Boston, MA",within an hour,100%,98%,f,Theater District,162,...,0,0,2022-09-11,2023-12-04,4.64,4.80,4.68,4.74,4.45,4.61
2600,2600,2024-12-20,2012-05-12,"Boston, MA",within an hour,84%,99%,f,Beacon Hill,73,...,1,0,2023-04-18,2023-12-23,4.00,4.00,3.00,5.00,5.00,4.00
2800,2800,2024-12-20,2022-12-26,NaN,within an hour,100%,99%,f,Cambridgeport,16,...,3,0,2023-07-09,2024-07-31,3.25,3.75,4.25,3.75,4.75,3.25
3000,3000,2024-12-20,2017-11-29,"Boston, MA",within an hour,90%,90%,t,Brighton,2,...,15,1,2023-12-10,2024-12-02,4.94,4.94,5.00,4.88,4.94,4.88
3200,3200,2024-12-20,2019-07-25,"Savannah, GA",within an hour,100%,100%,f,Midtown,8,...,22,2,2023-12-04,2024-12-03,4.75,4.63,4.92,4.92,4.50,4.50
3400,3400,2024-12-20,2013-10-13,"Boston, MA",within an hour,100%,100%,NaN,Back Bay,20,...,28,1,2023-12-11,2024-12-01,4.97,4.97,5.00,5.00,5.00,4.69
3600,3600,2024-12-20,2024-01-11,NaN,within an hour,100%,98%,f,Downtown,7,...,7,0,2024-03-31,2024-09-21,4.43,5.00,5.00,4.57,5.00,5.00
3800,3800,2024-12-20,2023-02-20,NaN,within an hour,99%,87%,f,Gateway District,3011,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4000,4000,2024-12-20,2012-03-28,"Boston, MA",within an hour,100%,80%,f,Columbus Park / Andrew Square,1,...,10,1,2024-08-25,2024-12-01,5.00,5.00,5.00,5.00,5.00,4.80
4200,4200,2024-12-20,2020-01-27,NaN,within an hour,100%,91%,f,Downtown,2,...,3,1,2024-11-03,2024-11-24,3.00,4.00,3.67,3.33,5.00,3.33
4400,4400,2024-12-20,2018-01-22,"Boston, MA",within an hour,100%,100%,f,Jamaica Plain,2,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Una vez listo ya solo lo exporte en forma de csv
df4.to_csv("Cuarto_punto.csv")

In [ ]:
#Ahora que lo analizo así pude resolver dos ejercicio anteriores, pero, aquí utilice el conector "or" para indicarle que solo filtrara por aquellas que fueran entire o en su caso, private room
df5 = df[(df['room_type']=='Entire home/apt') | (df['room_type'] == 'Private room')]
df5

,Unnamed: 0,last_scraped,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,...,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,0,2024-12-20,2008-12-03,"Massachusetts, United States",within a day,100%,22%,t,East Boston,2,...,1,0,2015-07-10,2024-08-09,4.96,5.00,5.00,4.96,4.85,4.88
1,1,2024-12-20,2009-02-19,"Boston, MA",within an hour,100%,99%,t,Roxbury,11,...,10,0,2009-03-21,2024-10-19,4.81,4.88,4.95,4.89,4.56,4.76
2,2,2024-12-20,2009-02-19,"Boston, MA",within an hour,100%,99%,t,Roxbury,11,...,8,0,2009-08-06,2024-11-11,4.81,4.83,4.91,4.95,4.53,4.72
3,3,2024-12-20,2009-07-22,"Boston, MA",within a few hours,100%,49%,t,Beacon Hill,8,...,1,0,2014-08-12,2024-05-15,4.69,4.69,4.93,4.97,4.97,4.59
4,4,2024-12-20,2009-09-16,NaN,within a day,91%,58%,f,Back Bay,22,...,0,0,2016-01-09,2019-07-22,4.33,4.44,4.56,4.00,5.00,4.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4421,4421,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4422,4422,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4423,4423,2024-12-20,2018-08-29,"Boston, MA",within an hour,100%,98%,f,Theater District,162,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4424,4424,2024-12-20,2016-05-29,NaN,within an hour,100%,100%,t,Roslindale,2,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4425,4425,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Una vez listo ya solo lo exporte en forma de csv
df5.to_csv("Quinto_punto.csv")

In [ ]:
#Aquí solo filtramos la columna denomidada "beds", e incluimos todos los valores que sean menores o iguales a 4
df6 = df[df['beds'] <= 4]
df6

,Unnamed: 0,last_scraped,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,...,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
1,1,2024-12-20,2009-02-19,"Boston, MA",within an hour,100%,99%,t,Roxbury,11,...,10,0,2009-03-21,2024-10-19,4.81,4.88,4.95,4.89,4.56,4.76
2,2,2024-12-20,2009-02-19,"Boston, MA",within an hour,100%,99%,t,Roxbury,11,...,8,0,2009-08-06,2024-11-11,4.81,4.83,4.91,4.95,4.53,4.72
3,3,2024-12-20,2009-07-22,"Boston, MA",within a few hours,100%,49%,t,Beacon Hill,8,...,1,0,2014-08-12,2024-05-15,4.69,4.69,4.93,4.97,4.97,4.59
4,4,2024-12-20,2009-09-16,NaN,within a day,91%,58%,f,Back Bay,22,...,0,0,2016-01-09,2019-07-22,4.33,4.44,4.56,4.00,5.00,4.67
5,5,2024-12-20,2009-09-16,NaN,within a day,91%,58%,f,Back Bay,22,...,0,0,2019-03-17,2023-11-19,5.00,5.00,5.00,5.00,5.00,4.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4421,4421,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4422,4422,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4423,4423,2024-12-20,2018-08-29,"Boston, MA",within an hour,100%,98%,f,Theater District,162,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4424,4424,2024-12-20,2016-05-29,NaN,within an hour,100%,100%,t,Roslindale,2,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4425,4425,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Una vez listo ya solo lo exporte en forma de csv
df6.to_csv("Sexto_punto.csv")

In [ ]:
#La columna que se filtrará será la que comprueba si es un superhost, y aquí como la categorización de los valores solo se da por true o false (abreviado), solo indicamos que seleccione los valores verdaderos o sea "t"
df7 = df[df['host_is_superhost']=='t']
df7

,Unnamed: 0,last_scraped,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,...,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,0,2024-12-20,2008-12-03,"Massachusetts, United States",within a day,100%,22%,t,East Boston,2,...,1,0,2015-07-10,2024-08-09,4.96,5.00,5.00,4.96,4.85,4.88
1,1,2024-12-20,2009-02-19,"Boston, MA",within an hour,100%,99%,t,Roxbury,11,...,10,0,2009-03-21,2024-10-19,4.81,4.88,4.95,4.89,4.56,4.76
2,2,2024-12-20,2009-02-19,"Boston, MA",within an hour,100%,99%,t,Roxbury,11,...,8,0,2009-08-06,2024-11-11,4.81,4.83,4.91,4.95,4.53,4.72
3,3,2024-12-20,2009-07-22,"Boston, MA",within a few hours,100%,49%,t,Beacon Hill,8,...,1,0,2014-08-12,2024-05-15,4.69,4.69,4.93,4.97,4.97,4.59
9,9,2024-12-20,2010-07-20,"Boston, MA",within a few hours,100%,67%,t,Jamaica Plain,1,...,4,1,2010-08-27,2024-12-11,4.98,4.95,4.97,4.94,4.93,4.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4404,4404,2024-12-20,2021-09-29,"Boston, MA",within an hour,100%,100%,t,Mattapan,12,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4405,4405,2024-12-20,2021-09-29,"Boston, MA",within an hour,100%,100%,t,Mattapan,12,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4411,4411,2024-12-20,2021-09-29,"Boston, MA",within an hour,100%,100%,t,Mattapan,12,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4414,4414,2024-12-20,2017-05-27,"Quincy, MA",within an hour,100%,100%,t,North Quincy,28,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4424,4424,2024-12-20,2016-05-29,NaN,within an hour,100%,100%,t,Roslindale,2,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Una vez listo ya solo lo exporte en forma de csv
df7.to_csv("Septimo_punto.csv")

In [ ]:
#Aquí como el filtro que aplicaremos será por la posición de los indices usamos el .iloc, y dentro de los parentesis indicaremos "las instrcciones" en las que el programa filtrará los datos, le decimos que empezará en la posición 1, no tendrá un límite donde paré, e irá en saltos de dos posiciones
df8 = df.iloc[1::2]
df8

,Unnamed: 0,last_scraped,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,...,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
1,1,2024-12-20,2009-02-19,"Boston, MA",within an hour,100%,99%,t,Roxbury,11,...,10,0,2009-03-21,2024-10-19,4.81,4.88,4.95,4.89,4.56,4.76
3,3,2024-12-20,2009-07-22,"Boston, MA",within a few hours,100%,49%,t,Beacon Hill,8,...,1,0,2014-08-12,2024-05-15,4.69,4.69,4.93,4.97,4.97,4.59
5,5,2024-12-20,2009-09-16,NaN,within a day,91%,58%,f,Back Bay,22,...,0,0,2019-03-17,2023-11-19,5.00,5.00,5.00,5.00,5.00,4.80
7,7,2024-12-20,2010-01-19,"Boston, MA",within a day,100%,97%,f,Dorchester,39,...,0,0,2010-05-12,2023-08-19,4.31,4.50,4.56,4.46,4.24,4.48
9,9,2024-12-20,2010-07-20,"Boston, MA",within a few hours,100%,67%,t,Jamaica Plain,1,...,4,1,2010-08-27,2024-12-11,4.98,4.95,4.97,4.94,4.93,4.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4417,4417,2024-12-20,2024-12-13,NaN,NaN,NaN,100%,f,South Boston,2,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4419,4419,2024-12-20,2016-04-14,"Boston, MA",NaN,NaN,NaN,f,Fenway–Kenmore,2,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4421,4421,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4423,4423,2024-12-20,2018-08-29,"Boston, MA",within an hour,100%,98%,f,Theater District,162,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4425,4425,2024-12-20,2020-10-28,"Boston, MA",within an hour,100%,97%,f,Harvard Square,199,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Una vez listo ya solo lo exporte en forma de csv
df8.to_csv("Octavo_punto.csv")